# Generated by Django 3.0 on 2025-01-24 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charging_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.CharField(max_length=100)),
                ('outlettype', models.CharField(max_length=100)),
                ('number_of_outlets', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel_Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fuelstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('licenseno', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('latitude', models.CharField(default='', max_length=50)),
                ('longitude', models.CharField(default='', max_length=50)),
                ('positive', models.BigIntegerField(default=0)),
                ('negative', models.BigIntegerField(default=0)),
                ('neutral', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=300)),
                ('pincode', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('certificate', models.CharField(max_length=500)),
                ('photo', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Worker_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('charge', models.CharField(max_length=100)),
                ('positive', models.BigIntegerField(default=0)),
                ('negative', models.BigIntegerField(default=0)),
                ('neutral', models.BigIntegerField(default=0)),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Workers')),
            ],
        ),
        migrations.CreateModel(
            name='Worker_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='', max_length=30)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
                ('WORKER_SERVICE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Worker_Service')),
            ],
        ),
        migrations.CreateModel(
            name='Work_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('FUEL', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Fuelstation')),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('slots', models.BigIntegerField(default=1)),
                ('CHARGINGPOINT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Charging_point')),
            ],
        ),
        migrations.CreateModel(
            name='Slotbooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('date', models.DateField(default='2024-06-10')),
                ('SLOTS', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Slots')),
                ('USER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('review', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
                ('WORKERSERVICE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Worker_Service')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='', max_length=30)),
                ('WORKER_REQUEST', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Worker_Request')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('charge', models.BigIntegerField()),
                ('WORKER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Workers')),
            ],
        ),
        migrations.CreateModel(
            name='Review_app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('review', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='', max_length=30)),
                ('SLOTBOOKING', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Slotbooking')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login'),
        ),
        migrations.CreateModel(
            name='Fuel_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=300)),
                ('quantity', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('stock', models.CharField(max_length=300)),
                ('FUEL', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Fuelstation')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='', max_length=30)),
                ('FUELBOOKING', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Fuel_Booking')),
            ],
        ),
        migrations.AddField(
            model_name='fuel_booking',
            name='FUEL_STOCK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Fuel_Stock'),
        ),
        migrations.AddField(
            model_name='fuel_booking',
            name='USER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Users'),
        ),
        migrations.CreateModel(
            name='Fs_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('review', models.CharField(max_length=100)),
                ('FS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Fuelstation')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Evstation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('licenseno', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('latitude', models.CharField(default='', max_length=50)),
                ('longitude', models.CharField(default='', max_length=50)),
                ('positive', models.CharField(default='', max_length=100)),
                ('negative', models.CharField(default='', max_length=100)),
                ('neutral', models.CharField(default='', max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Ev_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('review', models.CharField(max_length=100)),
                ('EV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Evstation')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=600)),
                ('type', models.CharField(max_length=90)),
                ('ex_date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Distruption_detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('reply', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=600)),
                ('date', models.DateField()),
                ('FROMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromc', to='myapp.Login')),
                ('TOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toc', to='myapp.Login')),
            ],
        ),
        migrations.AddField(
            model_name='charging_point',
            name='EV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Evstation'),
        ),
        migrations.CreateModel(
            name='Block_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_date', models.DateField()),
                ('time', models.TimeField()),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
            ],
        ),
    ]
