# Generated by Django 2.2.4 on 2025-02-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distruption_detection',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='document',
            name='USER',
        ),
        migrations.DeleteModel(
            name='Block_Info',
        ),
        migrations.DeleteModel(
            name='Distruption_detection',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
